### ISSUE TITLE
Why do I get a crash?

### ISSUE THREAD

**Issue by felix91gr** [kryzhovnik/rails_admin_tag_list#24]
I get the error: `NoMethodError in RailsAdmin::Main#show`

![image](https://user-images.githubusercontent.com/11747623/57153488-71092680-6da4-11e9-89cd-6633b94af567.png)

This is the class I'm using the tags from:

```ruby
class Story < ApplicationRecord
  translates :title, :summary, :content, :fallbacks_for_empty_translations => true
  accepts_nested_attributes_for :translations, allow_destroy: true

  has_paper_trail
  belongs_to :user
  belongs_to :story_category

  acts_as_taggable
  acts_as_taggable_on :tags

  has_one_attached :picture

end
```

Without this gem, I get a normal admin panel but without the tags:

![image](https://user-images.githubusercontent.com/11747623/57153641-d826db00-6da4-11e9-86ca-0b8f52de895e.png)

But if I'm using it, the admin panel crashes.

Does it have to do with the fact that my seeds assign no tags yet?
Or is the problem somewhere else?

Please help. I think I'm not getting something really obvious about the usage of the gem :pray:

**Comment by thatandromeda** [comment]
Not just you. I'm having this problem in the course of an upgrade to Rails 5.2. The gem worked with older dependency versions, but there's an incompatibility, I think either with 5.2 or with the version of acts_as_taggable_on I needed to upgrade to in order to use 5.2. This gem hasn't been updated in 3 years so I guess I shouldn't expect 5.2 compat, but I don't have a solution yet either.

**Comment by kryzhovnik** [comment]
Sorry for my absence. If the issue is still relevant for, check the gem's last version.

**Comment by felix91gr** [comment]
Thank you! :)
